### PR TITLE
bugfix: getEntityManager() in ODataJPAContext is not thread safe

### PR DESCRIPTION
**Pull request by met-pub**
issue see: https://github.com/eugenp/tutorials/issues/8821

### CODE REVIEW

**Comment by amaljoyc** [comment]
Looking forward to the merge!

**Comment by mcichowski** [comment]
Merge it!

**Comment by DJColdBrain** [comment]
Looking forward to the megre!

**Comment by mibo** [comment]
Created issue [OLINGO-1555](https://issues.apache.org/jira/browse/OLINGO-1555).

**Pull request merged**
