### PR TITLE
[OLINGO-605] Feature/olingo 605 xml adapter for properties

### PR DESCRIPTION
**Pull request by ManuelB**
Details can be found here:
https://issues.apache.org/jira/browse/OLINGO-605

### CODE REVIEW

**Comment by ManuelB** [comment]
Just hit the following problem:
```
06:44:39,015 ERROR [stderr] (default task-9) Caused by: org.apache.olingo.odata2.api.edm.EdmSimpleTypeException: The metadata constraints '[Nullable=true, MaxLength=255]' do not allow to format the value 'MULTIPOLYGON (((4458419.63 5343938.24, 4458395.73 5343927.45, 4458391.04 5343926.99, 42343450.1 5343907.92, 4458301.19 5343887.61, 4458297 5343894.81, 4458305.49 5343912.5, 4458313.13 5343928.43, 4458322.14 5343947.21, 4458328.43 5343972.9, 4458332.47 5343989.38, 4458369.33 5343993.28, 4458437.89 2342314.53, 4458553.12 42354313.86, 4458555.73 5344011.83, 4458498.07 5343979.64, 4458458.23 5343958.08, 4458425.61 5343942.69, 4458419.63 5343938.24)))'.
06:44:39,016 ERROR [stderr] (default task-9) at org.apache.olingo.odata2.core.edm.EdmString.internalValueToString(EdmString.java:80)
06:44:39,016 ERROR [stderr] (default task-9) at org.apache.olingo.odata2.core.edm.AbstractSimpleType.valueToString(AbstractSimpleType.java:112)
06:44:39,016 ERROR [stderr] (default task-9) at org.apache.olingo.odata2.core.ep.producer.XmlPropertyEntityProducer.appendProperty(XmlPropertyEntityProducer.java:201)
06:44:39,016 ERROR [stderr] (default task-9) at org.apache.olingo.odata2.core.ep.producer.XmlPropertyEntityProducer.append(XmlPropertyEntityProducer.java:67)
06:44:39,016 ERROR [stderr] (default task-9) ... 59 more
```
So I had to specify a length attribute on the column.

**Comment by deki** [comment]
Although I'm not an Olingo committer: You need do resolve the conflicts otherwise it's not possible to merge.

**Comment by ManuelB** [comment]
@deki this pull request is 2 years old before I spend more effort on making this work I will wait for an approval of an Olingo commiter. The guys have a lot of work and unfortunately merging pull requests is not their highest priority.

**Comment by deki** [comment]
Well currently release 2.0.9 is in progress and another PR got merged. Get in touch with @mibo, maybe there is a chance for an RC2.

**Comment by mibo** [comment]
Hi @ManuelB and @deki ,

I totally missed this pull request.
Sometimes it is bit unfamiliar to also check GitHub, but for this also the original Olingo issue somehow gets lost  ;o(

Unfortunately it will not get into the next release.
But if wished one of you can but it as discussion on the mailinglist if this extension can be part of the master.
At least I will pick the discussion up and if decided to add it we can work on the merge.

Regards, Michael

**Comment by ManuelB** [comment]
@mibo I will try to resolve the conflicts as soon as I some time.

**Comment by ManuelB** [comment]
@mibo  @deki I fixed the merge issues.

**Comment by mibo** [comment]
Fixed ([see commit 7aac7976](https://git-wip-us.apache.org/repos/asf?p=olingo-odata2.git;a=commit;h=7aac7976b3d576f3f24c8c0f4d75e0c7b1e96f95) and [OLINGO-605](https://issues.apache.org/jira/browse/OLINGO-605)).

**Comment by mibo** [comment]
Fixed ([see commit 7aac7976](https://git-wip-us.apache.org/repos/asf?p=olingo-odata2.git;a=commit;h=7aac7976b3d576f3f24c8c0f4d75e0c7b1e96f95) and [OLINGO-605](https://issues.apache.org/jira/browse/OLINGO-605)).

**Pull request closed without merging**
